services:
  app:
    build:
      dockerfile: ./Dockerfile
      target: app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8501:8501"
    environment:
      - MODEL_API_BASE_URL=http://model-api:8000
    depends_on:
      model-api:
        condition: service_healthy
  model-api:
    build:
      dockerfile: ./Dockerfile
      target: model-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://docker:password@postgres-db/submissions
    depends_on:
      postgres-db:
        condition: service_healthy
  postgres-db:
    build:
      dockerfile: ./Dockerfile
      target: postgres-db
    restart: unless-stopped
    shm_size: 128mb # Shared memory limit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: docker
      POSTGRES_DB: submissions
    healthcheck:
      test: pg_isready -U docker -d submissions
      start_interval: 1s
      timeout: 5s

volumes:
  postgres_data:
