[project]
name = "model-api"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "model",
    "fastapi[standard]>=0.115.12",
    "sqlmodel>=0.0.24",
    "psycopg2-binary>=2.9.10",
]

[build-system]
requires = ["hatchling"] # Required to make this importable as a package
build-backend = "hatchling.build"

[tool.uv.sources]
model = { workspace = true }
